# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-21 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pobox', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
