# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-21 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_name',
            new_name='name',
        ),
    ]
