# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-21 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'entries',
                'db_table': 'nano_blog_entry',
                'get_latest_by': 'pub_date',
                'ordering': ('-pub_date',),
            },
        ),
    ]
