# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-04 22:39
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
